### ISSUE TITLE
Suggestion: Change the name to sendgrid-java

### ISSUE THREAD

**Issue by motdotla** [sendgrid/sendgrid-google-java#1]
Hi @mariusrusu,

I'm enjoying this library. Should we change it to be named `sendgrid-java` ?

It seems like that would make more sense, and GitHub maintains the old pointer so it won't hurt anything. 

Thoughts?

**Comment by motdotla** [comment]
Ah, I see now that parts of it rely on Google App Engine though.

**Comment by mariusrusu** [comment]
Yes, we use some library from google:

import com.google.appengine.labs.repackaged.org.json.JSONException;
import com.google.appengine.labs.repackaged.org.json.JSONObject;
import com.google.appengine.labs.repackaged.org.json.JSONArray;

Maybe in the future we will create a library only for Java, without google dependency.

Thanks!

**Comment by motdotla** [comment]
Sounds good. You can close this.
