### ISSUE TITLE
String comparison should always be with equals

### ISSUE THREAD

**Issue by amiramit** [sendgrid/sendgrid-google-java#14]
@@ -646,7 +646,7 @@ public class Sendgrid {
                while (paramIterator.hasNext()) {
                        final String key = paramIterator.next();
                        final String value = data.get(key);
-                       if (key == "to" && this.getTos().size() > 0) {
-                       if (key.equals("to") && this.getTos().size() > 0) {
                              if (this._useHeaders() == true) {
                                      requestParams.append("to=" + value + "&"
                              } else {
  @@ -654,7 +654,7 @@ public class Sendgrid {
                                                      "to") + "&");
                              }
                      } else {
-                               if (key == "toname" && this.getToNames().size() 
-                               if (key.equals("toname") && this.getToNames().si
                                      requestParams.append(this._arrayToUrlPar
                                                      this.getToNames(), "tona
                                                      + "&");

**Comment by danielamihalache** [comment]
Fixed.
