### ISSUE TITLE
Does not support URL encode

### ISSUE THREAD

**Issue by awwa** [sendgrid/sendgrid-google-java#18]
If I set the value "abc+def@test.com" for from, API returns an error "Invalid email address abe def@test.com".
The problem is that the "+" is treated as white space.
Could you support "URL encode"?

Or 

sendgrid-java( https://github.com/sendgrid/sendgrid-java ) does not have the problem. But Google document has the reference to sendgrid-google-java.
Could you merge these libraries? These are similar.

**Comment by danielamihalache** [comment]
Fixed. Thanks for the feedback!
