### ISSUE TITLE
Public variable for messages is probably not the best way for error handling in Java

### ISSUE THREAD

**Issue by codenameone** [sendgrid/sendgrid-google-java#7]
While this is usable the API is odd and unintuitive to most Java developers, its perfectly OK to just throw an exception if the error is fatal or maybe provide a warning callback e.g. send(WarningCallback) where WarningCallback will be an optional interface that has a method like: warning(String message).

Thanks.

**Comment by danielamihalache** [comment]
Can you give me you email address to discuss about this?

**Comment by codenameone** [comment]
Sure, shai at codenameone dot com.
